### PR TITLE
Update to 4.5.4

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@JavkhlanK no prior experience with Flatpak, so help me out here when you've got time

**Comment by MrSquaare** [comment]
Build fails due to a .NET runtime version that doesn't match (at least).
This seems to be because the Avalonia dependencies have been modified (see https://github.com/ThePBone/GalaxyBudsClient/compare/4.5.2...4.5.4#diff-64647d3c5f8268908b6009c01f7aeb4647082a1c99529637691a473ab18fb4cf)
Never touched a C# project, I'll try to extract all dependencies for the two archs to also update sources-*.json files

**Comment by MrSquaare** [comment]
@vigress8 I created a PR on your own branch (https://github.com/vigress8/me.timschneeberger.GalaxyBudsClient/pull/1)

I simply used the [Flatpak .NET Generator tool](https://github.com/flatpak/flatpak-builder-tools/tree/master/dotnet) with the x64 and arm64 runtimes

**Comment by MrSquaare** [comment]
Also, I think it's better to move metadata and other Flatpak-related files into this repository rather than the source repository, to avoid having to create two PRs to update a version.

**Comment by ghost** [comment]
> Also, I think it's better to move metadata and other Flatpak-related files into this repository rather than the source repository, to avoid having to create two PRs to update a version.

I agree. This can be discussed under my draft PR:
ThePBone/GalaxyBudsClient#438
Or you may open an issue

**Comment by j-px** [comment]
Sorry, had some things to do. I'm not too sure about flatpak files being hosted just here, but in any case, I don't think any `<release>` tags should be removed, only appended. Maybe the change log from the GitHub Release should also be in the metainfo file. Anyway I think this PR is blocked by the PR in the actual app repo updating the metainfo file.

Also, the runtime should probably also be updated while we're at it :)

**Comment by ghost** [comment]
Seems like line 19 is the issue, but I don't have the knowledge to fix it.

**Comment by timschneeb** [comment]
I fixed the error, but there's a new issue about a version mismatch with Nuget packages.

**Comment by j-px** [comment]
This fails since it needs a linter exception.

From <https://docs.flathub.org/docs/for-app-authors/linter/>:
> Only exceptions to finish-args-wildcard-kde-own-name might be allowed in case of legacy tray usage.

Update: https://github.com/flathub-infra/flatpak-builder-lint/pull/279

**Comment by j-px** [comment]
bot, build me.timschneeberger.GalaxyBudsClient

**Comment by j-px** [comment]
Thanks everyone

**Pull request merged**
